### ISSUE TITLE
用群晖docker不成功

### ISSUE THREAD

**Issue by fanbin8592** [dnomd343/TProxy#1]
谢谢大佬这个项目，我自己研究过几天 没成功，然后发现了大佬的这个项目，很高兴，可是还是没成功。伤心
发现iptables 不能成功执行，手工执行也不成功。不知道为什么？

66d70dce6fc5:~# iptables-nft -t mangle -A XRAY -p udp -j TPROXY --on-ports 7288 --tproxy-mark 1      
iptables v1.8.7 (nf_tables): unknown option "--on-ports"                                             
Try `iptables -h' or 'iptables --help' for more information.                                         
66d70dce6fc5:~# iptables -t mangle -A XRAY -p udp -j TPROXY --on-ports 7288 --tproxy-mark 1          
iptables v1.8.7 (legacy): unknown option "--on-ports"                                                
Try `iptables -h' or 'iptables --help' for more information.                                         
66d70dce6fc5:~# apt install vim                                                                      
-ash: apt: not found                                                                                 
66d70dce6fc5:~# iptables -L                                                                          
Chain INPUT (policy ACCEPT)                                                                          
target     prot opt source               destination                                                 
                                                                                                     
Chain FORWARD (policy ACCEPT)                                                                        
target     prot opt source               destination                                                 
                                                                                                     
Chain OUTPUT (policy ACCEPT)                                                                         
target     prot opt source               destination   

还有xray的geoip那两个文件 没放在/usr/local/share/xray/   导致xray没跑起来。

**Comment by fanbin8592** [comment]
https://github.com/sjtuross/syno-iptables    是群晖的iptables不完整导致的

**Comment by dnomd343** [comment]
你好：

1. 命令中 `--on-ports` 应该改为 `--on-port`
2. 使用 `iptables` 与 `iptables-nft` 均可，前者基于legacy，后者为nf_tables
3. Docker镜像基于Alpine，你需要使用 `apk add ...` 命令而非 `apt install ...`
4. `geoip.dat` 与 `geosite.dat` 文件打包放置在 `/etc/xray/asset.tar.gz` ，运行时将其解压至 `/etc/xray/asset/` ，而后扫描 `/etc/xray/expose/asset/`（该目录暴露到容器外），若存在新的 `*.dat` 文件，则覆盖原有资源（外部更新，无需改动容器）；xray默认资源文件目录为 `/usr/local/share/xray/` ，但容器内部指定了环境变量 `XRAY_LOCATION_ASSET=/etc/xray/asset` ，运行时xray从该目录获取资源文件。

IPv4下的TProxy配置实例（IPv6类似）：
```bash
# 添加IPv4规则，让打上标记1的数据包走路由表100
ip -4 rule add fwmark 1 table 100

# 添加路由表100，数据包定向到localhost
ip -4 route add local 0.0.0.0/0 dev lo table 100

# 在iptables的mangle表上添加新的链XRAY
iptables -t mangle -N XRAY

# XRAY链中绕过部分特殊地址（如 `127.0.0.0/8`, `192.168.0.0/16`, `224.0.0.0/3`等）
iptables -t mangle -A XRAY -d {CIDR} -j RETURN

# 使用TProxy将流量发送到XRAY的7288端口
iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port 7288 --tproxy-mark 1
iptables -t mangle -A XRAY -p udp -j TPROXY --on-port 7288 --tproxy-mark 1

# 在mangle表的PREROUTING链上操作，让流量匹配XRAY链
iptables -t mangle -A PREROUTING -j XRAY
```

以上操作均在容器启动时自动进行，代码位于 [/tproxy.sh](https://github.com/dnomd343/TProxy/blob/master/tproxy.sh)，无需手动操作。

此外，你可以使用 `docker logs -f {容器ID}` 获取TProxy配置日志。

**Comment by fanbin8592** [comment]
4,geoip.dat 与 geosite.dat 文件打包放置在 /etc/xray/asset.tar.gz ，运行时将其解压至 /etc/xray/asset/ ，而后扫描 /etc/xray/expose/asset/（该目录暴露到容器外），若存在新的 *.dat 文件，则覆盖原有资源（外部更新，无效改动容器）；xray默认资源文件目录为 /usr/local/share/xray/ ，但容器内部指定了环境变量 XRAY_LOCATION_ASSET=/etc/xray/asset ，运行时xray从该目录获取资源文件。
我是放在/etc/xray/expose/asset/，但是不行 cp一份到 /usr/local/share/xray/  就行了。
群晖的iptables功能不全，导致容器里的iptables有问题。
总之，谢谢大佬可以用了

**Comment by dnomd343** [comment]
感谢使用😄
